### PR TITLE
Add time in notes card

### PR DESCRIPTION
**Pull request by ujwalkumar1995**
#4 
Hey @faisalamin001 
I have made the changes. Could you please review?

### CODE REVIEW

**Comment by faisalamin001** [comment]
Please remove the seconds from time and add `am, pm`

**Comment by ujwalkumar1995** [comment]
AM/PM is already added. I will remove seconds and commit.

**Comment by faisalamin001** [comment]
ok, thanks

**Comment by ujwalkumar1995** [comment]
Hey @faisalamin001 
I have made the suggested changes.

**Comment by faisalamin001** [comment]
Please add `am, pm`

Screenshot 2022-10-05 at 11 57 16 AM

**Comment by ujwalkumar1995** [comment]
It is showing up on my system. Not sure what the issue is. Let me try to figure it out.
Untitled

**Comment by faisalamin001** [comment]
You might not have pushed that code, I reviewed the pull request, and no such code exists related to `am, pm`

**Comment by ujwalkumar1995** [comment]
Hey @faisalamin001. The code was already pushed that was not the problem.
It could be something related to your local time settings or node version. Not really sure though.
I have although added an additional option in the date format to display it 12 hour format that should include AM/PM.
Let me know if this is working for you.

**Comment by faisalamin001** [comment]
Thanks

**Pull request merged**
